name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-123.0.dev

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  loggycian_flutter:
    path: ../
  gql: ^1.0.0+1
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true